on:
  push:
    branches:
      - main

  repository_dispatch:
    types:
      - webhook

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to Cloudflare Pages
    environment: Production
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Node dependencies
        run: yarn install --frozen-lockfile

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@5.2.0

      - name: Build
        run: gatsby build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}

      - name: Verify build
        run: ls -la public

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: a95bfbe5faab2e985d45b5533c8d91dc
          projectName: archive-algo-is
          directory: public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}